### ISSUE TITLE
Dates of taken photos?

### ISSUE THREAD

**Issue by jberglinds** [ptschandl/HAM10000_dataset#1]
Hi, 
In the [extract_pptx.py#L11-L12 ](https://github.com/ptschandl/HAM10000_dataset/blob/master/extract/extract_pptx.py#L11-L12) you mention the prerequisite that the .pptx files has to include a year in the filename. 

In the dataset published at https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/DBW86T I can find no dates for the photos. The exif data seems to have been stripped and the metadata doesn't contain dates either. 

Is there a way to get the dates for the photos? 
I'm trying to map out how skin lesions changes over time. 
I'm thankful for any pointers you can give me! 🙂

**Comment by ptschandl** [comment]
Hi @jberglinds 
Thanks for your interest in the dataset! Sorry that this answer took so long - I simply didn't see your question...
Getting the year was necessary for us to map the correct diagnoses during workup. That any non-provided metadata is stripped in published data is on purpose though - we don't include them for privacy reasons. So unfortunately: no, there is not way to get the dates.
